// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ziPyl2wfFyj6yGLJMRUxmB6vVLwutN0',
    appId: '1:853133921442:web:211dbe779ec5743631dbfb',
    messagingSenderId: '853133921442',
    projectId: 'factory-attendance-kel-6',
    authDomain: 'factory-attendance-kel-6.firebaseapp.com',
    storageBucket: 'factory-attendance-kel-6.firebasestorage.app',
    measurementId: 'G-P2XF6CR485',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYElweDlW_2jc21DEHI6R68x9CwfWLr40',
    appId: '1:853133921442:android:795c1b5355354c3931dbfb',
    messagingSenderId: '853133921442',
    projectId: 'factory-attendance-kel-6',
    storageBucket: 'factory-attendance-kel-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaIMLfevncmucswOm7BEL8bTiRRLysKg',
    appId: '1:853133921442:ios:92d583c610ef558f31dbfb',
    messagingSenderId: '853133921442',
    projectId: 'factory-attendance-kel-6',
    storageBucket: 'factory-attendance-kel-6.firebasestorage.app',
    iosBundleId: 'com.example.factoryAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaIMLfevncmucswOm7BEL8bTiRRLysKg',
    appId: '1:853133921442:ios:92d583c610ef558f31dbfb',
    messagingSenderId: '853133921442',
    projectId: 'factory-attendance-kel-6',
    storageBucket: 'factory-attendance-kel-6.firebasestorage.app',
    iosBundleId: 'com.example.factoryAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ziPyl2wfFyj6yGLJMRUxmB6vVLwutN0',
    appId: '1:853133921442:web:9f32fc2d6fcb742931dbfb',
    messagingSenderId: '853133921442',
    projectId: 'factory-attendance-kel-6',
    authDomain: 'factory-attendance-kel-6.firebaseapp.com',
    storageBucket: 'factory-attendance-kel-6.firebasestorage.app',
    measurementId: 'G-4JKS7GQZF4',
  );
}
